#!/usr/bin/env bash
# render-configs.sh - generate per-host wg0.conf from peers.txt + keys/
#
# Reads peers.txt (gitignored, operator-edited) and the keys produced
# by generate-keys.sh. Writes a complete /etc/wireguard/wg0.conf per
# peer into out/<peer>.conf with mode 0600.
#
# Usage:
#   ./render-configs.sh
#
# Env overrides:
#   WG_KEEPALIVE   PersistentKeepalive seconds (default: 25)
#   WG_PORT        ListenPort (default: 51820)
#
# Requires: wireguard-tools is NOT required here (only for genkey),
# but the keys/ directory must already be populated.

set -eu

DIR="$(cd "$(dirname "$0")" && pwd)"
PEERS_FILE="$DIR/peers.txt"
KEYS_DIR="$DIR/keys"
OUT_DIR="$DIR/out"

WG_KEEPALIVE="${WG_KEEPALIVE:-25}"
WG_PORT="${WG_PORT:-51820}"

if [ ! -f "$PEERS_FILE" ]; then
  echo "ERROR: $PEERS_FILE not found." >&2
  echo "  Copy peers.example.txt to peers.txt and edit before running." >&2
  exit 1
fi

if [ ! -d "$KEYS_DIR" ]; then
  echo "ERROR: $KEYS_DIR not found." >&2
  echo "  Run generate-keys.sh (or 'make wg-keys') first." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"
chmod 700 "$OUT_DIR"

# Parse peers.txt into parallel arrays. POSIX-ish: avoid herestrings.
NAMES=()
WG_IPS=()
ENDPOINTS=()
while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    ''|\#*) continue ;;
  esac
  set -- $line
  if [ "$#" -lt 3 ]; then
    echo "WARN: skipping malformed line in peers.txt: $line" >&2
    continue
  fi
  NAMES+=("$1")
  WG_IPS+=("$2")
  ENDPOINTS+=("$3")
done < "$PEERS_FILE"

if [ "${#NAMES[@]}" -eq 0 ]; then
  echo "ERROR: no peers parsed from $PEERS_FILE" >&2
  exit 1
fi

echo "Rendering wg0.conf for ${#NAMES[@]} peer(s) into $OUT_DIR/"
echo

for i in "${!NAMES[@]}"; do
  this_name="${NAMES[$i]}"
  this_ip="${WG_IPS[$i]}"
  priv_file="$KEYS_DIR/$this_name.priv"
  if [ ! -f "$priv_file" ]; then
    echo "ERROR: $priv_file missing - run generate-keys.sh first" >&2
    exit 1
  fi
  this_priv=$(cat "$priv_file")

  out_file="$OUT_DIR/$this_name.conf"
  {
    echo "# WireGuard mesh config for $this_name"
    echo "# Install at /etc/wireguard/wg0.conf (mode 0600, owner root)"
    echo "# Activate: systemctl enable --now wg-quick@wg0"
    echo "# Generated by render-configs.sh - do not hand-edit; re-render instead."
    echo
    echo "[Interface]"
    echo "PrivateKey = $this_priv"
    echo "Address = $this_ip/24"
    echo "ListenPort = $WG_PORT"
    echo "SaveConfig = false"
    echo

    for j in "${!NAMES[@]}"; do
      if [ "$i" = "$j" ]; then
        continue
      fi
      peer_name="${NAMES[$j]}"
      peer_ip="${WG_IPS[$j]}"
      peer_endpoint="${ENDPOINTS[$j]}"
      peer_pub_file="$KEYS_DIR/$peer_name.pub"
      if [ ! -f "$peer_pub_file" ]; then
        echo "ERROR: $peer_pub_file missing" >&2
        exit 1
      fi
      peer_pub=$(cat "$peer_pub_file")

      echo "# Peer: $peer_name"
      echo "[Peer]"
      echo "PublicKey = $peer_pub"
      echo "AllowedIPs = $peer_ip/32"
      if [ "$peer_endpoint" != "-" ] && [ -n "$peer_endpoint" ]; then
        echo "Endpoint = $peer_endpoint"
      fi
      echo "PersistentKeepalive = $WG_KEEPALIVE"
      echo
    done
  } > "$out_file"
  chmod 600 "$out_file"
  echo "  rendered: out/$this_name.conf"
done

echo
echo "Done. Per-host configs are in $OUT_DIR/ (mode 0600)."
echo
echo "Next: install on each host. Either:"
echo "  - 'make wg-install' if SSH is already reachable per peer endpoint, or"
echo "  - inject the conf via cloud-init for first-boot provisioning, or"
echo "  - manually: scp out/<peer>.conf <peer>:/etc/wireguard/wg0.conf"
echo "             then: systemctl enable --now wg-quick@wg0"
